### ISSUE TITLE
Implement logic for a linked list to be drawn on canvas

### ISSUE THREAD

**Issue by milad-aleali** [Reainheart/CST316JP#52]
- [x] On-click of:
  - [x] Canvas 
    - [x] creates a new node with a progressive id
    - [x] clears the selected objects
  - [x] Unselected Node, adds the node id to the selected objects
  - [x] Selected Node, removes the node id from the selected objects
  - [x] Canvas record gets updated
  - [x] Ctrl + Click adds to selected objects
  - [x] Selected objects are highlighted
- [ ] On key press event "d" or "Delete", delete the selected objects
- [x] Pointer logic implemented
  - If pointer is null, draw different arrow head
  - Draws the shortest possible perpendicular line between the objects selected
  - Draws pointer to cursor
  - Updates when cursor is moving on canvas
  - Highlights on hovering over another object
  - Arrow head snaps to object on hovering over another object
  - Pointer is deleted on-click
- [x] Implement start and end point storage
  - Start point is an object 
  - End point is a canvas coordinate or another object
- [x] On exiting object when selected, draws pointer
- [x] On-Click if Node is selected, if self-node is clicked, unselect

**Comment by Reainheart** [comment]
I got the selection tool to work
It adds things to the objects. I will make the changes tomorrow in the logic to make it have CTRL click and replacing the selected one without it

**Comment by Reainheart** [comment]
Pointer needs to be centered on the anchor points, we also need to get the toolbar in.
